name: Pull request pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Rust Graham Algorithm project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Diesel CLI
        run: cargo install diesel_cli --no-default-features --features postgres

      - name: Build
        run: cargo build --release --all-features
